services:
  epg-generator:
    build:
      context: ./epg_generator
      dockerfile: Dockerfile
    image: "procentric-epg-generator:local"
    pull_policy: never

  epg-admin:
    build:
      context: ./epg_admin
      dockerfile: Dockerfile
    image: "procentric-epg-admin:local"
    pull_policy: never
