apiVersion: v1
kind: Service
metadata:
  name: epg-admin
  namespace: procentric-epg
  labels:
    app: epg-admin
spec:
  type: ClusterIP
  selector:
    app: epg-admin
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
