apiVersion: v1
kind: Service
metadata:
  name: ftp-server-metrics
  namespace: procentric-epg
spec:
  type: ClusterIP
  selector:
    app: ftp-server
  ports:
    - name: metrics
      port: 10000
      targetPort: 10000
